from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path


JsonDocumentLoader = Callable[[Path], dict]


def test_cms_admin_uses_pinned_bundle_and_expected_collections(cms_build: Path) -> None:
    index = (cms_build / "admin" / "index.html").read_text(encoding="utf-8")
    config = (cms_build / "admin" / "config.yml").read_text(encoding="utf-8")

    assert "Generated by comic_git_engine" in index
    assert "noindex, nofollow" in index
    runtime_path = 'vendor/decap-cms-3.16.2-comic-git-b28103c19f4d/decap-cms.js'
    assert f'<script src="{runtime_path}"></script>' in index
    runtime_dir = cms_build / 'admin' / Path(runtime_path).parent
    manifest = json.loads(
        (runtime_dir / 'comic_git_engine_manifest.json').read_text(encoding='ascii')
    )
    assert manifest['asset_kind'] == 'comic_git_engine_decap_runtime'
    assert manifest['fork_commit'] == 'b28103c19f4d7fd6edb674022f1f71d744334214'
    assert (runtime_dir / 'decap-cms.js').is_file()
    assert not list(runtime_dir.glob('*.map'))

    assert "Generated by comic_git_engine" in config
    assert "  name: github" in config
    assert '  repo: "comic-git/cms-pages"' in config
    assert '  base_url: "https://auth.example.test"' in config
    assert config.index('name: "comic_settings"') < config.index(
        'name: "main_comic_pages"'
    )
    assert 'name: "main_comic_settings"' in config
    assert 'file: "your_content/comic_info.toml"' in config
    assert 'label: "Comic Details"' in config
    assert 'label: "Website"' in config
    assert 'label: "Links"' in config
    assert 'label: "Custom Pages"' in config
    assert 'summary: "{{fields.template_name}} — {{fields.title}}"' in config
    assert config.count("collapsed: true") == 9
    assert config.index('name: "main_comic_pages"') < config.index(
        'name: "extra_comic_1_side_story"'
    )
    assert 'folder: "your_content/comics"' in config
    assert 'folder: "your_content/side-story/comics"' in config
    assert 'path: "{{slug}}/info"' in config
    assert "delete: false" in config
    assert config.count('summary: "{{fields.title | default(\'Image\')}}"') == 2
    assert config.count('collapsed: false') == 4
    assert (
        config.count('label: "Hover text", name: "alt_text", widget: "string"') == 2
    )
    assert (
        config.count(
            'label: "Screen reader text", name: "screen_reader_text", widget: "string"'
        )
        == 2
    )
    assert config.count('summary: "{{post_date}} — {{title}}"') == 2
    assert config.count('{field: "post_date", default_sort: "desc"}') == 2
    assert config.count('      - "title"') == 2
    assert config.count('label: "Hover text", name: "alt_text"') == 4
    assert config.count('label: "Screen reader text", name: "screen_reader_text"') == 4
    assert 'field: {label: "Character"' not in config
    assert 'field: {label: "Tag"' not in config


def test_cms_fixture_remains_valid_normal_site_input(
    cms_build: Path,
    load_json_document: JsonDocumentLoader,
) -> None:
    main = load_json_document(cms_build / "comic" / "page_info_list.json")
    extra = load_json_document(
        cms_build / "side-story" / "comic" / "page_info_list.json"
    )

    assert [page["page_name"] for page in main["pages"]] == ["multi-image", "text-only"]
    assert [image["filename"] for image in main["pages"][0]["images"]] == [
        "first.svg",
        "second.svg",
    ]
    assert main["pages"][1]["images"] == []
    assert main["pages"][1]["title"] == "Text Only"
    assert [page["page_name"] for page in extra["pages"]] == ["extra-page"]
    assert (cms_build / "comic" / "text-only" / "index.html").is_file()
    assert (cms_build / "side-story" / "comic" / "extra-page" / "index.html").is_file()
