from __future__ import annotations

from collections.abc import Callable
from pathlib import Path


JsonDocumentLoader = Callable[[Path], dict]


def test_cms_admin_uses_pinned_bundle_and_expected_collections(cms_build: Path) -> None:
    index = (cms_build / "admin" / "index.html").read_text(encoding="utf-8")
    config = (cms_build / "admin" / "config.yml").read_text(encoding="utf-8")

    assert "Generated by comic_git_engine" in index
    assert "noindex, nofollow" in index
    assert "decap-cms@3.16.0/dist/decap-cms.js" in index

    assert "Generated by comic_git_engine" in config
    assert "  name: github" in config
    assert '  repo: "comic-git/cms-pages"' in config
    assert '  base_url: "https://auth.example.test"' in config
    assert config.index('name: "main_comic_pages"') < config.index(
        'name: "extra_comic_1_side_story"'
    )
    assert 'folder: "your_content/comics"' in config
    assert 'folder: "your_content/side-story/comics"' in config
    assert 'path: "{{slug}}/info"' in config
    assert "delete: false" in config
    assert 'summary: "{{fields.filename}}"' in config


def test_cms_fixture_remains_valid_normal_site_input(
    cms_build: Path,
    load_json_document: JsonDocumentLoader,
) -> None:
    main = load_json_document(cms_build / "comic" / "page_info_list.json")
    extra = load_json_document(
        cms_build / "side-story" / "comic" / "page_info_list.json"
    )

    assert [page["page_name"] for page in main["pages"]] == ["multi-image", "text-only"]
    assert [image["filename"] for image in main["pages"][0]["images"]] == [
        "first.svg",
        "second.svg",
    ]
    assert main["pages"][1]["images"] == []
    assert main["pages"][1]["title"] == "Text Only"
    assert [page["page_name"] for page in extra["pages"]] == ["extra-page"]
    assert (cms_build / "comic" / "text-only" / "index.html").is_file()
    assert (cms_build / "side-story" / "comic" / "extra-page" / "index.html").is_file()
